### ISSUE TITLE
Education Managed Distribution availability

### ISSUE THREAD

**Issue by DBartonKLA** [tougher/Brushes#15]
Good Afternoon,

We would like to push Brushes Redux out to our school using Device Assignment Managed Distribution (new feature introduced with iOS9 - assigns the license for the software directly to the device rather than the AppleID).

We were wondering when this feature will be made available to Brushes Redux, as our Art department would like students to begin using the application.

Appreciate any information which can be provided.

Thanks,
Dominic

**Comment by tougher** [comment]
Unfortunately I can't find any settings for this in iTunes Connect.

I only have 3 possible options for VPP in iTunes Connect (the first option is currently active):
<img width="793" alt="screen shot 2015-10-17 at 19 23 22" src="https://cloud.githubusercontent.com/assets/10697/10560236/d954ab16-7504-11e5-8867-4dc11b7796bd.png">

Got any ideas?

**Comment by tougher** [comment]
Found this downvoted and unanswered SO post addressing the same issue: http://stackoverflow.com/questions/32873397/how-to-enable-device-assigment-mode-for-vpp-with-free-apps

**Comment by DBartonKLA** [comment]
I'm not too sure, I've CC'd in someone from apple who has helped me in the
past to see if they can shed some light on how to get it to work for iOS 9
device assignment!

(Sorry for messaging out of the blue Tony hoping you can help.  We are
trying to get an App available to be distributed via iOS9 Device assignment
- currently it says "it has not yet been activated by the application's
publisher".  We would appreciate any help you can provide!)

*Kind Regards,*

*Dominic Barton*
Network Engineer
King's Leadership Academy Warrington
t. 01925 817939   e. D.Barton@kingswarrington.com

On 17 October 2015 at 18:39, tougher <notifications@github.com> wrote:

> Unfortunately I can't find any settings for this in iTunes Connect.
>
> I only have 3 possible options for VPP in iTunes Connect (the first option
> is currently active):
> [image: screen shot 2015-10-17 at 19 23 22]
> <https://cloud.githubusercontent.com/assets/10697/10560236/d954ab16-7504-11e5-8867-4dc11b7796bd.png>
>
> Got any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tougher/Brushes/issues/15#issuecomment-148937275>.
>

-- 


This email and any attachments to it may be confidential and are intended 
solely for the use of the individual to whom it is addressed. If you are 
not the intended recipient of this email, you must neither take any action 
based upon its contents, nor copy or show it to anyone.

Please contact the sender if you believe you have received this email in 
error.

**Comment by DBartonKLA** [comment]
Hi again,

I've spoken to Tony (support from Apple) and he said if you contact
developer support they will be able to get it sorted for you.

Best wishes,

*Kind Regards,*

*Dominic Barton*
Network Engineer
King's Leadership Academy Warrington
t. 01925 817939   e. D.Barton@kingswarrington.com

On 17 October 2015 at 18:46, tougher <notifications@github.com> wrote:

> Found this downvoted and unanswered SO post addressing the same issue:
> http://stackoverflow.com/questions/32873397/how-to-enable-device-assigment-mode-for-vpp-with-free-apps
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tougher/Brushes/issues/15#issuecomment-148937651>.
>

-- 


This email and any attachments to it may be confidential and are intended 
solely for the use of the individual to whom it is addressed. If you are 
not the intended recipient of this email, you must neither take any action 
based upon its contents, nor copy or show it to anyone.

Please contact the sender if you believe you have received this email in 
error.

**Comment by BChalcraft** [comment]
Any news on this feature? I'm looking to distribute in the same way but the app is still listed in my MDM (Meraki) as not device assignable, their tooltip simply says "Developers must update an app to enable device assignment".

Thanks


Ben Chalcraft
ICT Technician and Media Development Officer
The Innovation Centre Bradford

**Comment by robotech99** [comment]
Hello, can you please enable Device Assignment for this app?

My organization is moving away from installing apps using Apple IDs. Brushes Redux is the last of our core apps that does not support this feature. Previously I spoke with an Apple Consultant and they mentioned that it was a simple checkbox in iTunes Connect.

This thread mentions that a new agreement must be accepted... https://forums.developer.apple.com/thread/12580

"The great news for you: No changes to your apps are required in order to enable device-based licensing. All you need to do to be ready for iOS 9 is to review and accept the updated unified Developer Program License Agreement and the Paid Applications Schedule, if applicable, by following the steps below:

Log in to the Apple Developer Program Website
Navigate to Member Center
Review and accept the Unified Developer Program License Agreement
Log in to iTunes Connect
Navigate to the Agreements, Tax, and Banking module
Request the Paid Apps Amendment if available for request
This will take you to a screen displaying the updated contract terms, also available as a PDF download
Select the checkbox to agree to the amendment and click submit.
Make sure no other amendments are available for request.

For more information about the new features for managing devices in large organizations, refer to the WWDC Session Video What's New in Managing Apple Devices." 

https://developer.apple.com/videos/play/wwdc2015-301/

**Comment by BChalcraft** [comment]
Thanks guys, the status has changed and it's deploying fine for me now.

Ben Chalcraft
ICT Technician and Media Development Officer
The Innovation Centre Bradford

**Comment by DBartonKLA** [comment]
Same here for me, status has changed to allow device assignment and we are looking at rolling it out this afternoon.  Thank you for resolving this for us.
